[package]
name = "lib901p"
version = "0.1.0"
authors = ["Remy Goldschmidt <taktoa@gmail.com>"]
edition = "2018"

[dependencies]
serial = "*"

[lib]
name = "lib901p"
path = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/main.rs"

